/**
 * `pnpm --filter @pcpi/contracts gen` (root alias: `pnpm gen`)
 *
 * Boots the API's OpenAPI document generator (imports `apps/api/src/app.ts` directly by relative
 * path — deliberately not a workspace `dependency`, which would make a cycle with `@pcpi/api`
 * depending on `@pcpi/contracts`) and writes:
 *   - packages/contracts/openapi.json            (the OpenAPI 3.1 document)
 *   - packages/contracts/generated/client.d.ts   (openapi-typescript output)
 *
 * Both are committed. Run `pnpm build` first — this script imports `@pcpi/api`'s *source* via tsx,
 * but that source imports `@pcpi/contracts` and `@pcpi/core` by package name, which resolve to
 * their built `dist/` output.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';
// Relative, cross-package import by design — see file header.
import { createApp } from '../../../apps/api/src/app.js';

const here = dirname(fileURLToPath(import.meta.url));
const packageRoot = resolve(here, '..');
const openapiJsonPath = resolve(packageRoot, 'openapi.json');
const clientDtsPath = resolve(packageRoot, 'generated', 'client.d.ts');

const app = createApp();
const doc = app.getOpenAPI31Document({
  openapi: '3.1.0',
  info: { title: 'PC Parts Inventory API', version: '0.1.0' },
});

writeFileSync(openapiJsonPath, `${JSON.stringify(doc, null, 2)}\n`, 'utf-8');
console.log(`wrote ${openapiJsonPath}`);

const ast = await openapiTS(pathToFileURL(openapiJsonPath));
const contents = astToString(ast);

mkdirSync(dirname(clientDtsPath), { recursive: true });
writeFileSync(
  clientDtsPath,
  `/* Generated by \`pnpm gen\` from openapi.json — do not edit by hand. */\n${contents}`,
  'utf-8',
);
console.log(`wrote ${clientDtsPath}`);
