import type { SharedBuild, SharedBuildItem } from '@pcpi/contracts';
import { categoryLabel } from './category-labels.js';
import { itemDisplayName } from './item-name.js';
import { deltaPercent, formatCents, formatSignedCents, formatSignedPercent } from './money.js';
import { escapeMarkdownCell } from './text.js';

function itemPriceCell(item: SharedBuildItem): string {
  return item.currentCents != null ? formatCents(item.currentCents) : '—';
}

/**
 * PCPartPicker-style Markdown table (deliverable 1). Exactly one row per `build.items` entry —
 * the §7 integration gate asserts `share.md.rows == items`. Totals rows are omitted entirely when
 * `build.valuation` is absent (W0.3 may not exist on this branch) rather than showing a fake
 * "$0.00" or "NaN".
 */
export function renderShareMarkdown(build: SharedBuild, shareUrl: string): string {
  const lines: string[] = [];
  lines.push(`# ${escapeMarkdownCell(build.name)}`);
  lines.push('');
  lines.push('| Type | Item | Price |');
  lines.push('| --- | --- | --- |');

  for (const item of build.items) {
    const type = escapeMarkdownCell(categoryLabel(item.category));
    const name = escapeMarkdownCell(itemDisplayName(item));
    lines.push(`| ${type} | ${name} | ${itemPriceCell(item)} |`);
  }

  if (build.valuation) {
    const { acquiredCents, currentCents, deltaCents } = build.valuation;
    const pct = deltaPercent(acquiredCents, deltaCents);
    const deltaCell =
      pct != null
        ? `${formatSignedCents(deltaCents)} (${formatSignedPercent(pct)})`
        : formatSignedCents(deltaCents);
    lines.push(`| **Total (current)** | | **${formatCents(currentCents)}** |`);
    lines.push(`| **Total (paid)** | | **${formatCents(acquiredCents)}** |`);
    lines.push(`| **Delta** | | **${deltaCell}** |`);
  }

  lines.push('');
  lines.push(`*Generated by PC Parts Inventory — ${shareUrl} — ${new Date().toISOString()}*`);

  return `${lines.join('\n')}\n`;
}
