import type { SharedBuild, SharedBuildItem } from '@pcpi/contracts';
import { categoryLabel, valuationCaption } from '@pcpi/contracts';
import { itemDisplayName } from './item-name.js';
import { formatCents, formatSignedCents, formatSignedPercent } from './money.js';
import { escapeMarkdownCell } from './text.js';

function itemPriceCell(item: SharedBuildItem, currency: string): string {
  return item.currentCents != null ? formatCents(item.currentCents, currency) : '—';
}

/** `—` when there is nothing comparable to delta (Task 7: "no comparable items" and "no change"
 * are different facts — never render `0`/`+0.0%` for the former). */
function deltaCell(valuation: NonNullable<SharedBuild['valuation']>, currency: string): string {
  const { comparable } = valuation;
  if (comparable.items === 0) return '—';
  return comparable.deltaPct != null
    ? `${formatSignedCents(comparable.deltaCents, currency)} (${formatSignedPercent(comparable.deltaPct)})`
    : formatSignedCents(comparable.deltaCents, currency);
}

/**
 * PCPartPicker-style Markdown table (deliverable 1). Exactly one row per `build.items` entry —
 * the §7 integration gate asserts `share.md.rows == items`. Totals rows are omitted entirely when
 * `build.valuation` is absent rather than showing a fake "$0.00" or "NaN".
 *
 * Presentation (Task 7, architect, revised 2026-09-05): Paid / Now / Δ, with an explanatory italic
 * caption below from `valuationCaption` (`@pcpi/contracts`) — replaces the old "Total (current)/
 * Total (paid)/Delta" rows, which read the flat `deltaCents`/`deltaPct` the revised `Valuation`
 * contract no longer carries at the top level. The caption exists because `Paid`/`Now` sum over
 * different item sets (D5 no-fallback), so `Paid − Now` does not equal `Δ` in general — the caption
 * names which parts fed which number instead of leaving the reader to do that subtraction and get
 * confused. Same wording as the card, the share page and the build page — all four call
 * `valuationCaption` directly rather than each composing their own string.
 */
export function renderShareMarkdown(build: SharedBuild, shareUrl: string): string {
  const lines: string[] = [];
  lines.push(`# ${escapeMarkdownCell(build.name)}`);
  lines.push('');
  lines.push('| Type | Item | Price |');
  lines.push('| --- | --- | --- |');

  for (const item of build.items) {
    const type = escapeMarkdownCell(categoryLabel(item.category));
    const name = escapeMarkdownCell(itemDisplayName(item));
    lines.push(`| ${type} | ${name} | ${itemPriceCell(item, build.currency)} |`);
  }

  if (build.valuation) {
    const { acquiredCents, currentCents } = build.valuation;
    lines.push(`| **Paid** | | **${formatCents(acquiredCents, build.currency)}** |`);
    lines.push(`| **Now** | | **${formatCents(currentCents, build.currency)}** |`);
    lines.push(`| **Δ** | | **${deltaCell(build.valuation, build.currency)}** |`);
    lines.push('');
    lines.push(`*${valuationCaption(build.valuation)}*`);
  }

  lines.push('');
  lines.push(`*Generated by PC Parts Inventory — ${shareUrl} — ${new Date().toISOString()}*`);

  return `${lines.join('\n')}\n`;
}
