import type { SharedBuild, SharedBuildItem } from '@pcpi/contracts';
import { describe, expect, it } from 'vitest';
import { renderShareMarkdown } from '../../src/share/markdown.js';

function item(overrides: Partial<SharedBuildItem> = {}): SharedBuildItem {
  return {
    category: 'gpu',
    manufacturer: 'NVIDIA',
    model: 'GeForce RTX 4070',
    quantity: 1,
    currentCents: 47900,
    ...overrides,
  };
}

function build(overrides: Partial<SharedBuild> = {}): SharedBuild {
  return {
    slug: 'abc123defg',
    name: 'MOONPC',
    updatedAt: '2026-09-01T00:00:00.000Z',
    items: [item()],
    ...overrides,
  };
}

function countDataRows(md: string): number {
  return md
    .split('\n')
    .filter((line) => line.trim().startsWith('|'))
    .filter((line) => !/^\|\s*-+\s*\|/.test(line.trim()))
    .filter((line) => !line.includes('Type') || !line.includes('Item')) // drop the header row
    .filter((line) => !line.includes('**')).length; // drop totals rows
}

describe('renderShareMarkdown — row count', () => {
  it.each([1, 2, 10])('emits exactly one row per item for a %i-item build', (count) => {
    const items = Array.from({ length: count }, (_, i) =>
      item({ model: `Widget ${i}`, manufacturer: 'Acme' }),
    );
    const md = renderShareMarkdown(build({ items }), 'https://example.test/share/abc123defg');
    expect(countDataRows(md)).toBe(count);
  });
});

describe('renderShareMarkdown — structure', () => {
  it('starts with an H1 of the build name and the PCPartPicker-style header row', () => {
    const md = renderShareMarkdown(build(), 'https://example.test/share/abc123defg');
    expect(md.startsWith('# MOONPC\n')).toBe(true);
    expect(md).toContain('| Type | Item | Price |');
    expect(md).toContain('| --- | --- | --- |');
  });

  it('renders a human-readable category label, never the raw enum key', () => {
    const md = renderShareMarkdown(
      build({ items: [item({ category: 'cpu_cooler', manufacturer: 'Noctua', model: 'NH-D15' })] }),
      'https://example.test/share/abc123defg',
    );
    expect(md).toContain('| CPU Cooler | Noctua NH-D15 |');
  });

  it('renders quantity > 1 with a (×N) suffix', () => {
    const md = renderShareMarkdown(
      build({
        items: [
          item({
            category: 'memory',
            manufacturer: 'Corsair',
            model: 'Vengeance DDR5',
            quantity: 2,
            currentCents: 18999,
          }),
        ],
      }),
      'https://example.test/share/abc123defg',
    );
    expect(md).toContain('Corsair Vengeance DDR5 (×2)');
  });

  it('shows an em dash when an item has no currentCents, never $0.00 or NaN', () => {
    const md = renderShareMarkdown(
      build({ items: [item({ currentCents: undefined })] }),
      'https://example.test/share/abc123defg',
    );
    expect(md).toContain('—');
    expect(md).not.toContain('$0.00');
    expect(md).not.toContain('NaN');
  });

  it('includes the footer line with the share URL and an ISO date', () => {
    const md = renderShareMarkdown(build(), 'https://example.test/share/abc123defg');
    expect(md).toContain('Generated by PC Parts Inventory');
    expect(md).toContain('https://example.test/share/abc123defg');
    expect(md).toMatch(/\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/);
  });
});

describe('renderShareMarkdown — `|` and newline escaping', () => {
  it('escapes a pipe in an item name so it cannot split the table row', () => {
    const md = renderShareMarkdown(
      build({ items: [item({ manufacturer: 'Weird|Brand', model: 'Model' })] }),
      'https://example.test/share/abc123defg',
    );
    const row = md.split('\n').find((l) => l.includes('Weird'));
    expect(row).toBeDefined();
    expect(row).toContain('Weird\\|Brand');
    // A 3-column row has exactly 4 *unescaped* pipe delimiters (leading/2 separators/trailing);
    // the escaped one inside the item name must not be mistaken for a 5th column boundary.
    const unescapedPipes = (row?.match(/(?<!\\)\|/g) ?? []).length;
    expect(unescapedPipes).toBe(4);
  });

  it('collapses a newline embedded in an item name to a space', () => {
    const md = renderShareMarkdown(
      build({ items: [item({ manufacturer: 'Line1\nLine2', model: 'Model' })] }),
      'https://example.test/share/abc123defg',
    );
    expect(md).not.toMatch(/Line1\nLine2/);
    expect(md).toContain('Line1 Line2');
  });

  it('escapes a pipe in the build name (H1)', () => {
    const md = renderShareMarkdown(build({ name: 'My | Build' }), 'https://example.test');
    expect(md.startsWith('# My \\| Build')).toBe(true);
  });
});

describe('renderShareMarkdown — totals (present/absent with and without valuation)', () => {
  it('omits totals rows entirely when valuation is absent', () => {
    const md = renderShareMarkdown(build(), 'https://example.test');
    expect(md).not.toContain('Total (current)');
    expect(md).not.toContain('Total (paid)');
    expect(md).not.toContain('Delta');
  });

  it('renders Total (current), Total (paid) and a signed Delta when valuation is present', () => {
    const md = renderShareMarkdown(
      build({ valuation: { acquiredCents: 175000, currentCents: 189998, deltaCents: 14998 } }),
      'https://example.test',
    );
    expect(md).toContain('| **Total (current)** | | **$1,899.98** |');
    expect(md).toContain('| **Total (paid)** | | **$1,750.00** |');
    expect(md).toContain('+$149.98 (+8.6%)');
  });

  it('signs a negative delta with a minus and no fake percent when acquired is 0', () => {
    const md = renderShareMarkdown(
      build({ valuation: { acquiredCents: 0, currentCents: 0, deltaCents: -500 } }),
      'https://example.test',
    );
    expect(md).toContain('-$5.00');
    expect(md).not.toContain('NaN');
    expect(md).not.toContain('Infinity');
  });
});

describe('renderShareMarkdown — never leaks fields SharedBuild does not carry', () => {
  it('ignores serial/notes/acquiredSource even if a poisoned object smuggles them in', () => {
    const poisonedItem = {
      ...item(),
      serial: 'GPU-SN-0001',
      notes: 'bought used, has a scratch',
      acquiredSource: 'ebay-seller-xyz',
    } as SharedBuildItem;
    const poisonedBuild = {
      ...build({ items: [poisonedItem] }),
      owner: 'local',
      ownerId: 'owner-secret-id',
    } as SharedBuild;

    const md = renderShareMarkdown(poisonedBuild, 'https://example.test');

    expect(md).not.toContain('GPU-SN-0001');
    expect(md).not.toContain('scratch');
    expect(md).not.toContain('ebay-seller-xyz');
    expect(md).not.toContain('owner-secret-id');
    expect(md.toLowerCase()).not.toContain('serial');
  });
});
